image: binarno/imebra_docker_build

pipelines:
  default:
    - step:
        script:
          - alias python=python3
          - ant 
          - python uploadDropbox.py ./imebra_source_distribution.zip
